name = "licter-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "licter-db"
database_id = "1009c19a-ca6b-4db4-9e7a-91174de23dac"

[vars]
OPENAI_API_KEY = ""
GROQ_API_KEY = ""
MISTRAL_API_KEY = ""
